### ISSUE TITLE
jitpack.io publish issues

### ISSUE THREAD

**Issue by kolegych** [ybroeker/camunda-junit5#2]
Hi, the new artifacts are not published into jitpack.io

https://jitpack.io/com/github/ybroeker/camunda-junit5/0.0.6/build.log
https://jitpack.io/com/github/ybroeker/camunda-junit5/0.0.7/build.log

**Comment by ybroeker** [comment]
Thanks for the information!

Just released a new version which is available at jitpack: https://jitpack.io/#ybroeker/camunda-junit5/0.0.8

**Comment by kolegych** [comment]
Thanks for your quick response!
