### ISSUE TITLE
got Invalid parameter name ""

### ISSUE THREAD

**Issue by bisegni** [ybroeker/camunda-junit5#3]
I got the error in the title when TestProcessEngine need to be instantiated

**Comment by ybroeker** [comment]
Can you provide a stacktrace or minimal example?

**Comment by bisegni** [comment]
[for_github.zip](https://github.com/ybroeker/camunda-junit5/files/4093396/for_github.zip)

Hi Attach there are java test class file and all the log with the stack trace.
Than in advanced

**Comment by ybroeker** [comment]
Which JVM-Version do you run the test with?

Doesn't sound like something produced by this extension, more like a jvm-bug, e.g.: https://bugs.openjdk.java.net/browse/JDK-8170063

**Comment by bisegni** [comment]
oh thank you I was on old version jdk, installing new version all work well
